# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
archives_base_name=Switchy-Puffish-Skills

# mod metadata
group=dev.missy
user=semihoficial
slug=switchy-puffish-skills
modId=switchy_puffish_skills
modName=Switchy Pufferfish Skills
modDescription=Compatibility between Switchy and Pufferfish Skills
authors=mise_png/missypissy
license=GPL-3.0-or-later

# mod version
modVersion=1.0

# branch metadata
branch=1.21.1
tagBranch=1.21.1
compatibleVersions=1.21, 1.21.1
compatibleLoaders=fabric, quilt, neoforge
